<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.bluebridge</groupId>
    <artifactId>javase-tutorial</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>01-jdk-doc</module>
        <module>02-jdk-features</module>
        <module>03-jdk-concurrency</module>
        <module>04-jdk-source</module>
        <module>05-jdk-libs</module>
        <module>06-jdk-github</module>
        <module>07-data_structure</module>
        <module>08-algorithm</module>
        <module>09-design_patterns</module>
        <module>10-advanced</module>
        <module>11-exercises</module>
        <module>12-gui-awt</module>
        <module>13-gui-swing</module>
        <module>14-gui-javafx</module>
    </modules>
</project>