// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto
// Protobuf Java Version: 4.33.0

package org.bluebridge.protobuf.proto;

@com.google.protobuf.Generated
public final class ContactProto extends com.google.protobuf.GeneratedFile {
  private ContactProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ContactProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.contacts.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code org.bluebridge.protobuf.contacts.Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.contacts.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "Phone");
    }
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      number_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.ContactProto.Phone.class, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, number_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, number_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.ContactProto.Phone)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.ContactProto.Phone other = (org.bluebridge.protobuf.proto.ContactProto.Phone) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.ContactProto.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bluebridge.protobuf.contacts.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.contacts.Phone)
        org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.ContactProto.Phone.class, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.ContactProto.Phone.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        number_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Phone getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.ContactProto.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Phone build() {
        org.bluebridge.protobuf.proto.ContactProto.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Phone buildPartial() {
        org.bluebridge.protobuf.proto.ContactProto.Phone result = new org.bluebridge.protobuf.proto.ContactProto.Phone(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.ContactProto.Phone result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.number_ = number_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.ContactProto.Phone) {
          return mergeFrom((org.bluebridge.protobuf.proto.ContactProto.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.ContactProto.Phone other) {
        if (other == org.bluebridge.protobuf.proto.ContactProto.Phone.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.contacts.Phone)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.contacts.Phone)
    private static final org.bluebridge.protobuf.proto.ContactProto.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.ContactProto.Phone();
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeopleInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.contacts.PeopleInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone> 
        getPhonesList();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    org.bluebridge.protobuf.proto.ContactProto.Phone getPhones(int index);
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder> 
        getPhonesOrBuilderList();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder getPhonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.bluebridge.protobuf.contacts.PeopleInfo}
   */
  public static final class PeopleInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.contacts.PeopleInfo)
      PeopleInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "PeopleInfo");
    }
    // Use PeopleInfo.newBuilder() to construct.
    private PeopleInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PeopleInfo() {
      name_ = "";
      phones_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.class, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_ = 0;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone> phones_;
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    @java.lang.Override
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.Phone getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(3, phones_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, phones_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.ContactProto.PeopleInfo)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.ContactProto.PeopleInfo other = (org.bluebridge.protobuf.proto.ContactProto.PeopleInfo) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.ContactProto.PeopleInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bluebridge.protobuf.contacts.PeopleInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.contacts.PeopleInfo)
        org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.class, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        age_ = 0;
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
        } else {
          phones_ = null;
          phonesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo build() {
        org.bluebridge.protobuf.proto.ContactProto.PeopleInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo buildPartial() {
        org.bluebridge.protobuf.proto.ContactProto.PeopleInfo result = new org.bluebridge.protobuf.proto.ContactProto.PeopleInfo(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.bluebridge.protobuf.proto.ContactProto.PeopleInfo result) {
        if (phonesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            phones_ = java.util.Collections.unmodifiableList(phones_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.ContactProto.PeopleInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.ContactProto.PeopleInfo) {
          return mergeFrom((org.bluebridge.protobuf.proto.ContactProto.PeopleInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.ContactProto.PeopleInfo other) {
        if (other == org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (phonesBuilder_ == null) {
          if (!other.phones_.isEmpty()) {
            if (phones_.isEmpty()) {
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePhonesIsMutable();
              phones_.addAll(other.phones_);
            }
            onChanged();
          }
        } else {
          if (!other.phones_.isEmpty()) {
            if (phonesBuilder_.isEmpty()) {
              phonesBuilder_.dispose();
              phonesBuilder_ = null;
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000004);
              phonesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetPhonesFieldBuilder() : null;
            } else {
              phonesBuilder_.addAllMessages(other.phones_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                org.bluebridge.protobuf.proto.ContactProto.Phone m =
                    input.readMessage(
                        org.bluebridge.protobuf.proto.ContactProto.Phone.parser(),
                        extensionRegistry);
                if (phonesBuilder_ == null) {
                  ensurePhonesIsMutable();
                  phones_.add(m);
                } else {
                  phonesBuilder_.addMessage(m);
                }
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone> phones_ =
        java.util.Collections.emptyList();
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          phones_ = new java.util.ArrayList<org.bluebridge.protobuf.proto.ContactProto.Phone>(phones_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bluebridge.protobuf.proto.ContactProto.Phone, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder, org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder> phonesBuilder_;

      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone> getPhonesList() {
        if (phonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phones_);
        } else {
          return phonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public int getPhonesCount() {
        if (phonesBuilder_ == null) {
          return phones_.size();
        } else {
          return phonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.Phone getPhones(int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);
        } else {
          return phonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, org.bluebridge.protobuf.proto.ContactProto.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.set(index, value);
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder setPhones(
          int index, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder addPhones(org.bluebridge.protobuf.proto.ContactProto.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, org.bluebridge.protobuf.proto.ContactProto.Phone value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(index, value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder addPhones(
          org.bluebridge.protobuf.proto.ContactProto.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder addPhones(
          int index, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends org.bluebridge.protobuf.proto.ContactProto.Phone> values) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phones_);
          onChanged();
        } else {
          phonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public Builder removePhones(int index) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.remove(index);
          onChanged();
        } else {
          phonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.Phone.Builder getPhonesBuilder(
          int index) {
        return internalGetPhonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder getPhonesOrBuilder(
          int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);  } else {
          return phonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder> 
           getPhonesOrBuilderList() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phones_);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.Phone.Builder addPhonesBuilder() {
        return internalGetPhonesFieldBuilder().addBuilder(
            org.bluebridge.protobuf.proto.ContactProto.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.Phone.Builder addPhonesBuilder(
          int index) {
        return internalGetPhonesFieldBuilder().addBuilder(
            index, org.bluebridge.protobuf.proto.ContactProto.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.Phone phones = 3;</code>
       */
      public java.util.List<org.bluebridge.protobuf.proto.ContactProto.Phone.Builder> 
           getPhonesBuilderList() {
        return internalGetPhonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bluebridge.protobuf.proto.ContactProto.Phone, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder, org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder> 
          internalGetPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bluebridge.protobuf.proto.ContactProto.Phone, org.bluebridge.protobuf.proto.ContactProto.Phone.Builder, org.bluebridge.protobuf.proto.ContactProto.PhoneOrBuilder>(
                  phones_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.contacts.PeopleInfo)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.contacts.PeopleInfo)
    private static final org.bluebridge.protobuf.proto.ContactProto.PeopleInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.ContactProto.PeopleInfo();
    }

    public static org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PeopleInfo>
        PARSER = new com.google.protobuf.AbstractParser<PeopleInfo>() {
      @java.lang.Override
      public PeopleInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PeopleInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeopleInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.contacts.Contacts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> 
        getContactsList();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getContacts(int index);
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.bluebridge.protobuf.contacts.Contacts}
   */
  public static final class Contacts extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.contacts.Contacts)
      ContactsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "Contacts");
    }
    // Use Contacts.newBuilder() to construct.
    private Contacts(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Contacts() {
      contacts_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Contacts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.ContactProto.Contacts.class, org.bluebridge.protobuf.proto.ContactProto.Contacts.Builder.class);
    }

    public static final int CONTACTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> contacts_;
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    @java.lang.Override
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(1, contacts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contacts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.ContactProto.Contacts)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.ContactProto.Contacts other = (org.bluebridge.protobuf.proto.ContactProto.Contacts) obj;

      if (!getContactsList()
          .equals(other.getContactsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ContactProto.Contacts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.ContactProto.Contacts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.bluebridge.protobuf.contacts.Contacts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.contacts.Contacts)
        org.bluebridge.protobuf.proto.ContactProto.ContactsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Contacts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.ContactProto.Contacts.class, org.bluebridge.protobuf.proto.ContactProto.Contacts.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.ContactProto.Contacts.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
        } else {
          contacts_ = null;
          contactsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.ContactProto.internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Contacts getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.ContactProto.Contacts.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Contacts build() {
        org.bluebridge.protobuf.proto.ContactProto.Contacts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ContactProto.Contacts buildPartial() {
        org.bluebridge.protobuf.proto.ContactProto.Contacts result = new org.bluebridge.protobuf.proto.ContactProto.Contacts(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.bluebridge.protobuf.proto.ContactProto.Contacts result) {
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.ContactProto.Contacts result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.ContactProto.Contacts) {
          return mergeFrom((org.bluebridge.protobuf.proto.ContactProto.Contacts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.ContactProto.Contacts other) {
        if (other == org.bluebridge.protobuf.proto.ContactProto.Contacts.getDefaultInstance()) return this;
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.bluebridge.protobuf.proto.ContactProto.PeopleInfo m =
                    input.readMessage(
                        org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.parser(),
                        extensionRegistry);
                if (contactsBuilder_ == null) {
                  ensureContactsIsMutable();
                  contacts_.add(m);
                } else {
                  contactsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contacts_ = new java.util.ArrayList<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo>(contacts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bluebridge.protobuf.proto.ContactProto.PeopleInfo, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder, org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder setContacts(
          int index, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder setContacts(
          int index, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder addContacts(org.bluebridge.protobuf.proto.ContactProto.PeopleInfo value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder addContacts(
          int index, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder addContacts(
          org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder addContacts(
          int index, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends org.bluebridge.protobuf.proto.ContactProto.PeopleInfo> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder getContactsBuilder(
          int index) {
        return internalGetContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public java.util.List<? extends org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder addContactsBuilder() {
        return internalGetContactsFieldBuilder().addBuilder(
            org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder addContactsBuilder(
          int index) {
        return internalGetContactsFieldBuilder().addBuilder(
            index, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.bluebridge.protobuf.contacts.PeopleInfo contacts = 1;</code>
       */
      public java.util.List<org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder> 
           getContactsBuilderList() {
        return internalGetContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bluebridge.protobuf.proto.ContactProto.PeopleInfo, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder, org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder> 
          internalGetContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bluebridge.protobuf.proto.ContactProto.PeopleInfo, org.bluebridge.protobuf.proto.ContactProto.PeopleInfo.Builder, org.bluebridge.protobuf.proto.ContactProto.PeopleInfoOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.contacts.Contacts)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.contacts.Contacts)
    private static final org.bluebridge.protobuf.proto.ContactProto.Contacts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.ContactProto.Contacts();
    }

    public static org.bluebridge.protobuf.proto.ContactProto.Contacts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contacts>
        PARSER = new com.google.protobuf.AbstractParser<Contacts>() {
      @java.lang.Override
      public Contacts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Contacts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contacts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.ContactProto.Contacts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_contacts_Phone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_contacts_Contacts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022 org.bluebridge.protobu" +
      "f.contacts\032\raddress.proto\"\027\n\005Phone\022\016\n\006nu" +
      "mber\030\001 \001(\t\"`\n\nPeopleInfo\022\014\n\004name\030\001 \001(\t\022\013" +
      "\n\003age\030\002 \001(\005\0227\n\006phones\030\003 \003(\0132\'.org.bluebr" +
      "idge.protobuf.contacts.Phone\"J\n\010Contacts" +
      "\022>\n\010contacts\030\001 \003(\0132,.org.bluebridge.prot" +
      "obuf.contacts.PeopleInfoB/\n\035org.bluebrid" +
      "ge.protobuf.protoB\014ContactProtoP\000b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bluebridge.protobuf.proto.AddressProto.getDescriptor(),
        });
    internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_org_bluebridge_protobuf_contacts_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_contacts_Phone_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_contacts_PeopleInfo_descriptor,
        new java.lang.String[] { "Name", "Age", "Phones", });
    internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_org_bluebridge_protobuf_contacts_Contacts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_contacts_Contacts_descriptor,
        new java.lang.String[] { "Contacts", });
    descriptor.resolveAllFeaturesImmutable();
    org.bluebridge.protobuf.proto.AddressProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
