// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.33.0

package org.bluebridge.protobuf.proto;

@com.google.protobuf.Generated
public final class UserProto extends com.google.protobuf.GeneratedFile {
  private UserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "UserProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.protobuf.color.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 字段格式：[规则] 类型 字段名 = 字段编号;
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @return A list containing the tags.
     */
    java.util.List<java.lang.String>
        getTagsList();
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @return The count of tags.
     */
    int getTagsCount();
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    java.lang.String getTags(int index);
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);

    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     * @return The address.
     */
    org.bluebridge.protobuf.proto.UserProto.Address getAddress();
    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     */
    org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * <pre>
   * 5. 定义消息（类似 Java 的 Class）：用户信息
   * </pre>
   *
   * Protobuf type {@code org.bluebridge.protobuf.protobuf.color.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.protobuf.color.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "User");
    }
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.UserProto.User.class, org.bluebridge.protobuf.proto.UserProto.User.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <pre>
     * 字段格式：[规则] 类型 字段名 = 字段编号;
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_ = 0;
    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int TAGS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_;
    }
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * 标签（repeated 对应 Java 的 List&lt;String&gt;）
     * </pre>
     *
     * <code>repeated string tags = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private org.bluebridge.protobuf.proto.UserProto.Address address_;
    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     * @return The address.
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.UserProto.Address getAddress() {
      return address_ == null ? org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance() : address_;
    }
    /**
     * <pre>
     * 嵌套消息（对应 Java 的内部类 Address）
     * </pre>
     *
     * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
     */
    @java.lang.Override
    public org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, tags_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getAddress());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += computeStringSizeNoTag(tags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAddress());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.UserProto.User)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.UserProto.User other = (org.bluebridge.protobuf.proto.UserProto.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.UserProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 5. 定义消息（类似 Java 的 Class）：用户信息
     * </pre>
     *
     * Protobuf type {@code org.bluebridge.protobuf.protobuf.color.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.protobuf.color.User)
        org.bluebridge.protobuf.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.UserProto.User.class, org.bluebridge.protobuf.proto.UserProto.User.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        age_ = 0;
        tags_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.User getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.UserProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.User build() {
        org.bluebridge.protobuf.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.User buildPartial() {
        org.bluebridge.protobuf.proto.UserProto.User result = new org.bluebridge.protobuf.proto.UserProto.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.UserProto.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.age_ = age_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          tags_.makeImmutable();
          result.tags_ = tags_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.address_ = addressBuilder_ == null
              ? address_
              : addressBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.UserProto.User) {
          return mergeFrom((org.bluebridge.protobuf.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.UserProto.User other) {
        if (other == org.bluebridge.protobuf.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ |= 0x00000008;
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                age_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureTagsIsMutable();
                tags_.add(s);
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    internalGetAddressFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * 字段格式：[规则] 类型 字段名 = 字段编号;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 字段格式：[规则] 类型 字段名 = 字段编号;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 字段格式：[规则] 类型 字段名 = 字段编号;
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名（必填逻辑需自己在 Java 中判断，proto3 默认可选）
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {

        age_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000004);
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureTagsIsMutable() {
        if (!tags_.isModifiable()) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @return A list containing the tags.
       */
      public com.google.protobuf.ProtocolStringList
          getTagsList() {
        tags_.makeImmutable();
        return tags_;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @return The count of tags.
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param index The index of the element to return.
       * @return The tags at the given index.
       */
      public java.lang.String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the tags at the given index.
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param index The index to set the value at.
       * @param value The tags to set.
       * @return This builder for chaining.
       */
      public Builder setTags(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTagsIsMutable();
        tags_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param value The tags to add.
       * @return This builder for chaining.
       */
      public Builder addTags(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureTagsIsMutable();
        tags_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param values The tags to add.
       * @return This builder for chaining.
       */
      public Builder addAllTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTags() {
        tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 标签（repeated 对应 Java 的 List&lt;String&gt;）
       * </pre>
       *
       * <code>repeated string tags = 4;</code>
       * @param value The bytes of the tags to add.
       * @return This builder for chaining.
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureTagsIsMutable();
        tags_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private org.bluebridge.protobuf.proto.UserProto.Address address_;
      private com.google.protobuf.SingleFieldBuilder<
          org.bluebridge.protobuf.proto.UserProto.Address, org.bluebridge.protobuf.proto.UserProto.Address.Builder, org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder> addressBuilder_;
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       * @return The address.
       */
      public org.bluebridge.protobuf.proto.UserProto.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public Builder setAddress(org.bluebridge.protobuf.proto.UserProto.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public Builder setAddress(
          org.bluebridge.protobuf.proto.UserProto.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public Builder mergeAddress(org.bluebridge.protobuf.proto.UserProto.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            address_ != null &&
            address_ != org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance()) {
            getAddressBuilder().mergeFrom(value);
          } else {
            address_ = value;
          }
        } else {
          addressBuilder_.mergeFrom(value);
        }
        if (address_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public org.bluebridge.protobuf.proto.UserProto.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return internalGetAddressFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      public org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <pre>
       * 嵌套消息（对应 Java 的内部类 Address）
       * </pre>
       *
       * <code>.org.bluebridge.protobuf.protobuf.color.Address address = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bluebridge.protobuf.proto.UserProto.Address, org.bluebridge.protobuf.proto.UserProto.Address.Builder, org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder> 
          internalGetAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bluebridge.protobuf.proto.UserProto.Address, org.bluebridge.protobuf.proto.UserProto.Address.Builder, org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.protobuf.color.User)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.protobuf.color.User)
    private static final org.bluebridge.protobuf.proto.UserProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.UserProto.User();
    }

    public static org.bluebridge.protobuf.proto.UserProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.UserProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.protobuf.color.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 省份
     * </pre>
     *
     * <code>string province = 1;</code>
     * @return The province.
     */
    java.lang.String getProvince();
    /**
     * <pre>
     * 省份
     * </pre>
     *
     * <code>string province = 1;</code>
     * @return The bytes for province.
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <pre>
     * 城市
     * </pre>
     *
     * <code>string city = 2;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <pre>
     * 城市
     * </pre>
     *
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <pre>
     * 详细地址
     * </pre>
     *
     * <code>string detail = 3;</code>
     * @return The detail.
     */
    java.lang.String getDetail();
    /**
     * <pre>
     * 详细地址
     * </pre>
     *
     * <code>string detail = 3;</code>
     * @return The bytes for detail.
     */
    com.google.protobuf.ByteString
        getDetailBytes();
  }
  /**
   * <pre>
   * 6. 在 user.proto 中定义嵌套消息（地址信息）
   * </pre>
   *
   * Protobuf type {@code org.bluebridge.protobuf.protobuf.color.Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.protobuf.color.Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "Address");
    }
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      province_ = "";
      city_ = "";
      detail_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.UserProto.Address.class, org.bluebridge.protobuf.proto.UserProto.Address.Builder.class);
    }

    public static final int PROVINCE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object province_ = "";
    /**
     * <pre>
     * 省份
     * </pre>
     *
     * <code>string province = 1;</code>
     * @return The province.
     */
    @java.lang.Override
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 省份
     * </pre>
     *
     * <code>string province = 1;</code>
     * @return The bytes for province.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <pre>
     * 城市
     * </pre>
     *
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 城市
     * </pre>
     *
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DETAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object detail_ = "";
    /**
     * <pre>
     * 详细地址
     * </pre>
     *
     * <code>string detail = 3;</code>
     * @return The detail.
     */
    @java.lang.Override
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 详细地址
     * </pre>
     *
     * <code>string detail = 3;</code>
     * @return The bytes for detail.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(province_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, province_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, city_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(detail_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, detail_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(province_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, province_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, city_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(detail_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, detail_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.UserProto.Address)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.UserProto.Address other = (org.bluebridge.protobuf.proto.UserProto.Address) obj;

      if (!getProvince()
          .equals(other.getProvince())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getDetail()
          .equals(other.getDetail())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvince().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + DETAIL_FIELD_NUMBER;
      hash = (53 * hash) + getDetail().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.UserProto.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.UserProto.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.UserProto.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.UserProto.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 6. 在 user.proto 中定义嵌套消息（地址信息）
     * </pre>
     *
     * Protobuf type {@code org.bluebridge.protobuf.protobuf.color.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.protobuf.color.Address)
        org.bluebridge.protobuf.proto.UserProto.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.UserProto.Address.class, org.bluebridge.protobuf.proto.UserProto.Address.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.UserProto.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        province_ = "";
        city_ = "";
        detail_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.UserProto.internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.Address getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.Address build() {
        org.bluebridge.protobuf.proto.UserProto.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.UserProto.Address buildPartial() {
        org.bluebridge.protobuf.proto.UserProto.Address result = new org.bluebridge.protobuf.proto.UserProto.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.UserProto.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.province_ = province_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.detail_ = detail_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.UserProto.Address) {
          return mergeFrom((org.bluebridge.protobuf.proto.UserProto.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.UserProto.Address other) {
        if (other == org.bluebridge.protobuf.proto.UserProto.Address.getDefaultInstance()) return this;
        if (!other.getProvince().isEmpty()) {
          province_ = other.province_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDetail().isEmpty()) {
          detail_ = other.detail_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                province_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                detail_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object province_ = "";
      /**
       * <pre>
       * 省份
       * </pre>
       *
       * <code>string province = 1;</code>
       * @return The province.
       */
      public java.lang.String getProvince() {
        java.lang.Object ref = province_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 省份
       * </pre>
       *
       * <code>string province = 1;</code>
       * @return The bytes for province.
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        java.lang.Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 省份
       * </pre>
       *
       * <code>string province = 1;</code>
       * @param value The province to set.
       * @return This builder for chaining.
       */
      public Builder setProvince(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        province_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 省份
       * </pre>
       *
       * <code>string province = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProvince() {
        province_ = getDefaultInstance().getProvince();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 省份
       * </pre>
       *
       * <code>string province = 1;</code>
       * @param value The bytes for province to set.
       * @return This builder for chaining.
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        province_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <pre>
       * 城市
       * </pre>
       *
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 城市
       * </pre>
       *
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 城市
       * </pre>
       *
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 城市
       * </pre>
       *
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 城市
       * </pre>
       *
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object detail_ = "";
      /**
       * <pre>
       * 详细地址
       * </pre>
       *
       * <code>string detail = 3;</code>
       * @return The detail.
       */
      public java.lang.String getDetail() {
        java.lang.Object ref = detail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 详细地址
       * </pre>
       *
       * <code>string detail = 3;</code>
       * @return The bytes for detail.
       */
      public com.google.protobuf.ByteString
          getDetailBytes() {
        java.lang.Object ref = detail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 详细地址
       * </pre>
       *
       * <code>string detail = 3;</code>
       * @param value The detail to set.
       * @return This builder for chaining.
       */
      public Builder setDetail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        detail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 详细地址
       * </pre>
       *
       * <code>string detail = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDetail() {
        detail_ = getDefaultInstance().getDetail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 详细地址
       * </pre>
       *
       * <code>string detail = 3;</code>
       * @param value The bytes for detail to set.
       * @return This builder for chaining.
       */
      public Builder setDetailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        detail_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.protobuf.color.Address)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.protobuf.color.Address)
    private static final org.bluebridge.protobuf.proto.UserProto.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.UserProto.Address();
    }

    public static org.bluebridge.protobuf.proto.UserProto.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.UserProto.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_protobuf_color_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_protobuf_color_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022&org.bluebridge.protobuf.pr" +
      "otobuf.color\"}\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name" +
      "\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\014\n\004tags\030\004 \003(\t\022@\n\007add" +
      "ress\030\005 \001(\0132/.org.bluebridge.protobuf.pro" +
      "tobuf.color.Address\"9\n\007Address\022\020\n\010provin" +
      "ce\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\016\n\006detail\030\003 \001(\tB," +
      "\n\035org.bluebridge.protobuf.protoB\tUserPro" +
      "toP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_org_bluebridge_protobuf_protobuf_color_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_protobuf_color_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Tags", "Address", });
    internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_org_bluebridge_protobuf_protobuf_color_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_protobuf_color_Address_descriptor,
        new java.lang.String[] { "Province", "City", "Detail", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
